name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: npm install
      - name: Install Dependencies
        run: npm install -g eslint 
      - name: Compile
        run: npm run compile
      - name: Lint
        run: eslint . --ext .ts,.tsx